"""password 63 hash

Revision ID: 40d8c4dfec0c
Revises: b044633c7f5b
Create Date: 2018-02-11 02:41:56.824946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40d8c4dfec0c'
down_revision = 'b044633c7f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=63), nullable=False))
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', mysql.VARCHAR(length=31), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
