"""add passwd

Revision ID: 5c30158f6742
Revises: 5ae5b01f1afb
Create Date: 2018-02-11 00:39:31.184470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c30158f6742'
down_revision = '5ae5b01f1afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', sa.String(length=31), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###
