"""password hash

Revision ID: 82d1fe2e1dd0
Revises: 5c30158f6742
Create Date: 2018-02-11 02:34:19.688412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d1fe2e1dd0'
down_revision = '5c30158f6742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
