"""password 63 hash

Revision ID: b044633c7f5b
Revises: 82d1fe2e1dd0
Create Date: 2018-02-11 02:39:00.417060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b044633c7f5b'
down_revision = '82d1fe2e1dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
