"""add timestamp

Revision ID: d37bb5687418
Revises: 0f5fa580f321
Create Date: 2018-01-19 04:50:09.329885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37bb5687418'
down_revision = '0f5fa580f321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'datetime')
    # ### end Alembic commands ###
